CREATE TABLE ordenes_compra (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proveedor_id BIGINT NOT NULL,
    fecha_creacion TIMESTAMP(6) NOT NULL,
    estado VARCHAR(20) NOT NULL,
    total NUMERIC(15, 2) NOT NULL,
    motivo_cancelacion VARCHAR(500),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT ck_orden_compra_estado CHECK (estado IN ('PENDIENTE', 'COMPLETADA', 'CANCELADA')),
    CONSTRAINT ck_orden_compra_total CHECK (total >= 0)
);

CREATE INDEX idx_ordenes_compra_proveedor ON ordenes_compra (proveedor_id);
CREATE INDEX idx_ordenes_compra_estado ON ordenes_compra (estado);
CREATE INDEX idx_ordenes_compra_fecha ON ordenes_compra (fecha_creacion);

CREATE TABLE detalles_orden_compra (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden_compra_id BIGINT NOT NULL,
    producto_id BIGINT NOT NULL,
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC(15, 2) NOT NULL,
    subtotal NUMERIC(15, 2) NOT NULL,
    CONSTRAINT fk_detalle_compra_orden
        FOREIGN KEY (orden_compra_id) REFERENCES ordenes_compra (id) ON DELETE CASCADE,
    CONSTRAINT uk_detalle_compra_producto UNIQUE (orden_compra_id, producto_id),
    CONSTRAINT ck_detalle_compra_cantidad CHECK (cantidad > 0),
    CONSTRAINT ck_detalle_compra_precio CHECK (precio_unitario > 0),
    CONSTRAINT ck_detalle_compra_subtotal CHECK (subtotal > 0)
);

CREATE INDEX idx_detalle_compra_orden ON detalles_orden_compra (orden_compra_id);
